---
services:
  maven:
    build:
      context: ./
    container_name: maven
    volumes:
      - app_data:/build
      - app_data:/usr/local/tomcat/webapps

  tomcat:
    image: tomcat:jre8-alpine
    depends_on:
      - maven
    container_name: tomcat
    ports:
      - '8080:8080'
    volumes:
      - app_data:/usr/local/tomcat/webapps

volumes:
  app_data: